# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleChat
  pod 'Socket.IO-Client-Swift', '~> 13.1.0'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'NSObject+Rx'
end
